name 'grafana'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures grafana'
long_description 'Installs/Configures grafana'
version '0.1.0'
